/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchParameters } from './searchParameters';

export interface EnvelopeSearchFilterObject { 
    query?: SearchParameters;
    /**
     * Geometry as string in WKT format.
     */
    geometry?: string;
    /**
     * Flag for search locally or globally.  default=false
     */
    localOnly?: boolean;
    /**
     * The public certificate(s) of the sender. Used to verify the envelope signature.
     */
    envelopeSignatureCertificate: Array<string>;
    /**
     * Claimed Thumbprint for Signed Root Key (X.509 Certificate) SHA256 and base64 as format
     */
    envelopeRootCertificateThumbprint: string;
    /**
     * Time stamp when the envelope is signed
     */
    envelopeSignatureTime: Date;
}