/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceInstanceObject } from './serviceInstanceObject';

/**
 * Information output from Service Registry search
 */
export interface EnvelopeUploadSearchResultObject { 
    /**
     * List of Service Instances found
     */
    serviceInstance: Array<ServiceInstanceObject>;
}