/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse200 {
  [key: string]: any;


}