/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Maritime Service (MS) types as defined by IMO/IALA/IMO-IHO harmonisation group.
 */
export type MaritimeServiceType = 'MS 1 – VTS Information Service (INS)' | 'MS 2 – VTS Navigational Assistance Service (NAS)' | 'MS 3 – Traffic Organization Service (TOS)' | 'MS 4 – Port Support Service (PSS)' | 'MS 5 – Maritime Safety Information (MSI) Service' | 'MS 6 – Pilotage Service' | 'MS 7 – Tug Service)' | 'MS 8 – Vessel Shore Reporting' | 'MS 9 – Telemedical Assistance Service (TMAS)' | 'MS 10 – Maritime Assistance Service (MAS)' | 'MS 11 – Nautical Chart Service' | 'MS 12 – Nautical Publications Service' | 'MS 13 – Ice Navigation Service' | 'MS 14 – Meteorological Information Service' | 'MS 15 – Real-Time Hydrographic & Environmental Information Service' | 'MS 16 – Search and Rescue (SAR) Service' | 'OTHER';

export const MaritimeServiceType = {
    MS1VTSInformationServiceINS: 'MS 1 – VTS Information Service (INS)' as MaritimeServiceType,
    MS2VTSNavigationalAssistanceServiceNAS: 'MS 2 – VTS Navigational Assistance Service (NAS)' as MaritimeServiceType,
    MS3TrafficOrganizationServiceTOS: 'MS 3 – Traffic Organization Service (TOS)' as MaritimeServiceType,
    MS4PortSupportServicePSS: 'MS 4 – Port Support Service (PSS)' as MaritimeServiceType,
    MS5MaritimeSafetyInformationMSIService: 'MS 5 – Maritime Safety Information (MSI) Service' as MaritimeServiceType,
    MS6PilotageService: 'MS 6 – Pilotage Service' as MaritimeServiceType,
    MS7TugService: 'MS 7 – Tug Service)' as MaritimeServiceType,
    MS8VesselShoreReporting: 'MS 8 – Vessel Shore Reporting' as MaritimeServiceType,
    MS9TelemedicalAssistanceServiceTMAS: 'MS 9 – Telemedical Assistance Service (TMAS)' as MaritimeServiceType,
    MS10MaritimeAssistanceServiceMAS: 'MS 10 – Maritime Assistance Service (MAS)' as MaritimeServiceType,
    MS11NauticalChartService: 'MS 11 – Nautical Chart Service' as MaritimeServiceType,
    MS12NauticalPublicationsService: 'MS 12 – Nautical Publications Service' as MaritimeServiceType,
    MS13IceNavigationService: 'MS 13 – Ice Navigation Service' as MaritimeServiceType,
    MS14MeteorologicalInformationService: 'MS 14 – Meteorological Information Service' as MaritimeServiceType,
    MS15RealTimeHydrographicEnvironmentalInformationService: 'MS 15 – Real-Time Hydrographic & Environmental Information Service' as MaritimeServiceType,
    MS16SearchAndRescueSARService: 'MS 16 – Search and Rescue (SAR) Service' as MaritimeServiceType,
    OTHER: 'OTHER' as MaritimeServiceType
};