/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnvelopeRetrieveResultObject } from './envelopeRetrieveResultObject';

/**
 * Information input retrieve result from previous search
 */
export interface RetrieveResultObject { 
    envelope: EnvelopeRetrieveResultObject;
    /**
     * The signature of the EnvelopeObject in HEX format without whitespace or linebreaks
     */
    envelopeSignature: string;
}