/**
 * MSR Interface definitions
 * Compliant with IEC 63173-2:2025 SECOM version 2
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SearchObjectResult { 
    instanceId?: string;
    version?: string;
    name?: string;
    status?: string;
    description?: string;
    dataProductType?: string;
    organizationId?: string;
    endpointUri?: string;
    endpointType?: string;
    keywords?: Array<string>;
    unlocode?: Array<string>;
    implementsDesigns?: Array<string>;
    apiDoc?: string;
    instanceAsXml?: string;
    mmsi?: string;
    imo?: string;
    sourceMSRs?: Array<string>;
    unsupportedParams?: Array<string>;
    coverageArea?: Array<string>;
    certificates?: Array<string>;
}