/**
 * MSR Interface definitions
 * Compliant with IEC 63173-2:2025 SECOM version 2
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SearchParameters { 
    name?: string;
    status?: string;
    version?: string;
    keywords?: Array<string>;
    description?: string;
    specificationId?: string;
    designId?: string;
    instanceId?: string;
    organisationId?: string;
    mmsi?: string;
    imo?: string;
    serviceType?: string;
    unlocode?: string;
    endpointUri?: string;
    dataProductType?: string;
    localOnly?: boolean;
}