/**
 * MSR Interface definitions
 * Compliant with IEC 63173-2:2025 SECOM version 2
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type SecomDataProductTypeEnum = 'S57' | 'S101' | 'S102' | 'S104' | 'S111' | 'S122' | 'S123' | 'S124' | 'S125' | 'S126' | 'S127' | 'S128' | 'S129' | 'S210' | 'S211' | 'S212' | 'S401' | 'S402' | 'S411' | 'S412' | 'S413' | 'S414' | 'S421' | 'RTZ' | 'EPC' | 'OTHER';

export const SecomDataProductTypeEnum = {
    S57: 'S57' as SecomDataProductTypeEnum,
    S101: 'S101' as SecomDataProductTypeEnum,
    S102: 'S102' as SecomDataProductTypeEnum,
    S104: 'S104' as SecomDataProductTypeEnum,
    S111: 'S111' as SecomDataProductTypeEnum,
    S122: 'S122' as SecomDataProductTypeEnum,
    S123: 'S123' as SecomDataProductTypeEnum,
    S124: 'S124' as SecomDataProductTypeEnum,
    S125: 'S125' as SecomDataProductTypeEnum,
    S126: 'S126' as SecomDataProductTypeEnum,
    S127: 'S127' as SecomDataProductTypeEnum,
    S128: 'S128' as SecomDataProductTypeEnum,
    S129: 'S129' as SecomDataProductTypeEnum,
    S210: 'S210' as SecomDataProductTypeEnum,
    S211: 'S211' as SecomDataProductTypeEnum,
    S212: 'S212' as SecomDataProductTypeEnum,
    S401: 'S401' as SecomDataProductTypeEnum,
    S402: 'S402' as SecomDataProductTypeEnum,
    S411: 'S411' as SecomDataProductTypeEnum,
    S412: 'S412' as SecomDataProductTypeEnum,
    S413: 'S413' as SecomDataProductTypeEnum,
    S414: 'S414' as SecomDataProductTypeEnum,
    S421: 'S421' as SecomDataProductTypeEnum,
    RTZ: 'RTZ' as SecomDataProductTypeEnum,
    EPC: 'EPC' as SecomDataProductTypeEnum,
    OTHER: 'OTHER' as SecomDataProductTypeEnum
};