/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Service Instance Status, One of Provisional(0), Released(1), Deprecated(2), Deleted(3)
 */
export enum ServiceInstanceStatus {
    PROVISIONAL = 0,
    RELEASED = 1,
    DEPRECATED = 2,
    DELETED = 3
}