/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ServiceInstanceStatus } from './serviceInstanceStatus';

/**
 * Service Instance Object returned from Service Registry search
 */
export interface ServiceInstanceObject { 
    /**
     * The MRN of the instance. This must match the MRN in the instance’s certificate.
     */
    instanceId: string;
    /**
     * Version number of the instance. Semantic versioning should be preferred.
     */
    version: string;
    /**
     * Name of service.
     */
    name: string;
    status: ServiceInstanceStatus;
    /**
     * Human-readable description of service.
     */
    description?: string;
    /**
     * A JSON array of strings that define the datatypes.
     */
    dataProductType?: Array<string>;
    /**
     * The MRN of the provider of the service.
     */
    organizationId: string;
    /**
     * The endpoint of the service. The format and completeness of the endpoint depend on the endpoint type.
     */
    endpointUri: string;
    /**
     * An array of the protocol fields of the transport of the service (e.g. REST, SECOM, MMS).
     */
    endpointType?: Array<string>;
    /**
     * A JSON array of keyword strings, e.g. [\"navigation\", \"warning\", \"navWarn\", \"s-124\"].
     */
    keywords?: Array<string>;
    /**
     * An array of UN/LOCODEs that describe the coverage area of the service.
     */
    unlocode?: Array<string>;
    /**
     * The MRNs of the service design the service that is implemented.
     */
    implementsDesigns?: Array<string>;
    /**
     * The URL to the documentation of the instance. Preferably not only API documentation but also necessary contact information, etc.
     */
    apiDoc?: string;
    /**
     * Strings in WKT format defining the coverage area of the service.
     */
    coverageArea: Array<string>;
    /**
     * IMO number for a ship
     */
    imo?: number;
    /**
     * MMSI number for a ship
     */
    mmsi?: number;
    /**
     * Public certificate x.509 in PEM format. Should include all currently valid certificates of the instance.
     */
    certificates?: Array<string>;
    /**
     * When result is from global search, the MRNs of the MSRs that returned the result.
     */
    sourceMSRs?: Array<string>;
    /**
     * A list of parameters that were not supported in the search.   In global search all parameters must be forwarded.   This must be empty / unset when returned as a result of retrieveResult.
     */
    unsupportedParams?: Array<string>;
}