/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EnvelopeUploadSearchResultObject } from './envelopeUploadSearchResultObject';

export interface UploadSearchResultObject { 
    envelope: EnvelopeUploadSearchResultObject;
    /**
     * The signature of the EnvelopeObject in HEX format without whitespace or linebreaks
     */
    envelopeSignature: string;
}