/**
 * MSR Interface definitions
 * Compliant with IEC 63173-2:2025 SECOM version 2
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DefaultResponseObject } from '../model/defaultResponseObject';
import { SearchFilterObject } from '../model/searchFilterObject';
import { SearchObjectResult } from '../model/searchObjectResult';
import { SearchResult } from '../model/searchResult';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SECOMService {

    protected basePath = '';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param transactionId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2RetrieveResultsTransactionIdGet(transactionId: string, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public v2RetrieveResultsTransactionIdGet(transactionId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public v2RetrieveResultsTransactionIdGet(transactionId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public v2RetrieveResultsTransactionIdGet(transactionId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (transactionId === null || transactionId === undefined) {
            throw new Error('Required parameter transactionId was null or undefined when calling v2RetrieveResultsTransactionIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SearchResult>('get',`${this.basePath}/api/secom/v2/retrieveResults/${encodeURIComponent(String(transactionId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param name 
     * @param status 
     * @param version 
     * @param keywords 
     * @param description 
     * @param specificationId 
     * @param designId 
     * @param instanceId 
     * @param organisationId 
     * @param mmsi 
     * @param imo 
     * @param serviceType 
     * @param unlocode 
     * @param endpointUri 
     * @param dataProductType 
     * @param localOnly 
     * @param geometry 
     * @param includeXml 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2SearchServiceGet(name?: string, status?: string, version?: string, keywords?: Array<string>, description?: string, specificationId?: string, designId?: string, instanceId?: string, organisationId?: string, mmsi?: number, imo?: number, serviceType?: string, unlocode?: string, endpointUri?: string, dataProductType?: string, localOnly?: boolean, geometry?: string, includeXml?: boolean, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public v2SearchServiceGet(name?: string, status?: string, version?: string, keywords?: Array<string>, description?: string, specificationId?: string, designId?: string, instanceId?: string, organisationId?: string, mmsi?: number, imo?: number, serviceType?: string, unlocode?: string, endpointUri?: string, dataProductType?: string, localOnly?: boolean, geometry?: string, includeXml?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public v2SearchServiceGet(name?: string, status?: string, version?: string, keywords?: Array<string>, description?: string, specificationId?: string, designId?: string, instanceId?: string, organisationId?: string, mmsi?: number, imo?: number, serviceType?: string, unlocode?: string, endpointUri?: string, dataProductType?: string, localOnly?: boolean, geometry?: string, includeXml?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public v2SearchServiceGet(name?: string, status?: string, version?: string, keywords?: Array<string>, description?: string, specificationId?: string, designId?: string, instanceId?: string, organisationId?: string, mmsi?: number, imo?: number, serviceType?: string, unlocode?: string, endpointUri?: string, dataProductType?: string, localOnly?: boolean, geometry?: string, includeXml?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }
        if (status !== undefined && status !== null) {
            queryParameters = queryParameters.set('status', <any>status);
        }
        if (version !== undefined && version !== null) {
            queryParameters = queryParameters.set('version', <any>version);
        }
        if (keywords) {
            keywords.forEach((element) => {
                queryParameters = queryParameters.append('keywords', <any>element);
            })
        }
        if (description !== undefined && description !== null) {
            queryParameters = queryParameters.set('description', <any>description);
        }
        if (specificationId !== undefined && specificationId !== null) {
            queryParameters = queryParameters.set('specificationId', <any>specificationId);
        }
        if (designId !== undefined && designId !== null) {
            queryParameters = queryParameters.set('designId', <any>designId);
        }
        if (instanceId !== undefined && instanceId !== null) {
            queryParameters = queryParameters.set('instanceId', <any>instanceId);
        }
        if (organisationId !== undefined && organisationId !== null) {
            queryParameters = queryParameters.set('organisationId', <any>organisationId);
        }
        if (mmsi !== undefined && mmsi !== null) {
            queryParameters = queryParameters.set('mmsi', <any>mmsi);
        }
        if (imo !== undefined && imo !== null) {
            queryParameters = queryParameters.set('imo', <any>imo);
        }
        if (serviceType !== undefined && serviceType !== null) {
            queryParameters = queryParameters.set('serviceType', <any>serviceType);
        }
        if (unlocode !== undefined && unlocode !== null) {
            queryParameters = queryParameters.set('unlocode', <any>unlocode);
        }
        if (endpointUri !== undefined && endpointUri !== null) {
            queryParameters = queryParameters.set('endpointUri', <any>endpointUri);
        }
        if (dataProductType !== undefined && dataProductType !== null) {
            queryParameters = queryParameters.set('dataProductType', <any>dataProductType);
        }
        if (localOnly !== undefined && localOnly !== null) {
            queryParameters = queryParameters.set('localOnly', <any>localOnly);
        }
        if (geometry !== undefined && geometry !== null) {
            queryParameters = queryParameters.set('geometry', <any>geometry);
        }
        if (includeXml !== undefined && includeXml !== null) {
            queryParameters = queryParameters.set('includeXml', <any>includeXml);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SearchResult>('get',`${this.basePath}/api/secom/v2/searchService`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public search(body?: SearchFilterObject, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public search(body?: SearchFilterObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public search(body?: SearchFilterObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public search(body?: SearchFilterObject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        console.log('Base path is:', this.basePath);
        return this.httpClient.request<SearchResult>('post',`${this.basePath}/api/secom/v2/searchService`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param instanceId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2UpdateServiceInstanceIdPut(instanceId: string, body?: { [key: string]: any; }, observe?: 'body', reportProgress?: boolean): Observable<Array<DefaultResponseObject>>;
    public v2UpdateServiceInstanceIdPut(instanceId: string, body?: { [key: string]: any; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DefaultResponseObject>>>;
    public v2UpdateServiceInstanceIdPut(instanceId: string, body?: { [key: string]: any; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DefaultResponseObject>>>;
    public v2UpdateServiceInstanceIdPut(instanceId: string, body?: { [key: string]: any; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (instanceId === null || instanceId === undefined) {
            throw new Error('Required parameter instanceId was null or undefined when calling v2UpdateServiceInstanceIdPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<DefaultResponseObject>>('put',`${this.basePath}/v2/updateService/${encodeURIComponent(String(instanceId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param transactionId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2UploadResultsTransactionIdPost(transactionId: string, body?: Array<SearchObjectResult>, observe?: 'body', reportProgress?: boolean): Observable<Array<DefaultResponseObject>>;
    public v2UploadResultsTransactionIdPost(transactionId: string, body?: Array<SearchObjectResult>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DefaultResponseObject>>>;
    public v2UploadResultsTransactionIdPost(transactionId: string, body?: Array<SearchObjectResult>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DefaultResponseObject>>>;
    public v2UploadResultsTransactionIdPost(transactionId: string, body?: Array<SearchObjectResult>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (transactionId === null || transactionId === undefined) {
            throw new Error('Required parameter transactionId was null or undefined when calling v2UploadResultsTransactionIdPost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<DefaultResponseObject>>('post',`${this.basePath}/v2/uploadResults/${encodeURIComponent(String(transactionId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
