/**
 * SECOM Service discovery interface
 * Compliant with SECOM IEC 63173-2 v2.0
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DefaultResponseObject } from '../model/defaultResponseObject';
import { MaritimeServiceType } from '../model/maritimeServiceType';
import { RetrieveResultObject } from '../model/retrieveResultObject';
import { SearchFilterObject } from '../model/searchFilterObject';
import { SearchResult } from '../model/searchResult';
import { ServiceInstanceStatus } from '../model/serviceInstanceStatus';
import { UpdateServiceObject } from '../model/updateServiceObject';
import { UploadSearchResultObject } from '../model/uploadSearchResultObject';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ServiceRegistryService {

    protected basePath = 'http://localhost:8444/api/secom';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param instanceId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiG1191V2UpdateServiceInstanceIdPut(instanceId: string, body?: UpdateServiceObject, observe?: 'body', reportProgress?: boolean): Observable<Array<DefaultResponseObject>>;
    public apiG1191V2UpdateServiceInstanceIdPut(instanceId: string, body?: UpdateServiceObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DefaultResponseObject>>>;
    public apiG1191V2UpdateServiceInstanceIdPut(instanceId: string, body?: UpdateServiceObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DefaultResponseObject>>>;
    public apiG1191V2UpdateServiceInstanceIdPut(instanceId: string, body?: UpdateServiceObject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (instanceId === null || instanceId === undefined) {
            throw new Error('Required parameter instanceId was null or undefined when calling apiG1191V2UpdateServiceInstanceIdPut.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<DefaultResponseObject>>('put',`${this.basePath}/api/g1191/v2/updateService/${encodeURIComponent(String(instanceId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param transactionId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiG1191V2UploadResultsTransactionIdPost(transactionId: string, body?: Array<UploadSearchResultObject>, observe?: 'body', reportProgress?: boolean): Observable<Array<DefaultResponseObject>>;
    public apiG1191V2UploadResultsTransactionIdPost(transactionId: string, body?: Array<UploadSearchResultObject>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DefaultResponseObject>>>;
    public apiG1191V2UploadResultsTransactionIdPost(transactionId: string, body?: Array<UploadSearchResultObject>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DefaultResponseObject>>>;
    public apiG1191V2UploadResultsTransactionIdPost(transactionId: string, body?: Array<UploadSearchResultObject>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (transactionId === null || transactionId === undefined) {
            throw new Error('Required parameter transactionId was null or undefined when calling apiG1191V2UploadResultsTransactionIdPost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Array<DefaultResponseObject>>('post',`${this.basePath}/api/g1191/v2/uploadResults/${encodeURIComponent(String(transactionId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This operation asks for result from global search based on given transaction identifier from previous search
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2RetrieveResultPost(body?: RetrieveResultObject, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public v2RetrieveResultPost(body?: RetrieveResultObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public v2RetrieveResultPost(body?: RetrieveResultObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public v2RetrieveResultPost(body?: RetrieveResultObject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SearchResult>('post',`${this.basePath}/v2/retrieveResult`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This operation searches for service using REST method GET. If no parameters given, a complete list of local services is given in result.
     * 
     * @param name Name of service.
     * @param status Status of service. One of “provisional”, “released”, “deprecated” or “deleted”.
     * @param version Version number of the instance. Semantic versioning should be preferred.
     * @param keywords A JSON array of keyword strings, e.g. [\&quot;navigation\&quot;, \&quot;warning\&quot;, \&quot;navWarn\&quot;, \&quot;s-124\&quot;].
     * @param description Human-readable description of service.
     * @param dataProductType A JSON array of strings that define the datatypes.
     * @param specificationId The MRN of the service specification.
     * @param designId The MRN of the service design.
     * @param instanceId The MRN of the service instance.
     * @param mmsi MMSI number for a ship
     * @param imo IMO number for a ship
     * @param serviceType Maritime Service (MS) types as defined by IMO/IALA/IMO-IHO harmonisation group.
     * @param unlocode An array of UN/LOCODEs that describe the coverage area of the service.
     * @param endpointUri The endpoint of the service. The format and completeness of the endpoint depend on the endpoint type.
     * @param geometry 
     * @param localOnly 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2SearchServiceGet(name?: string, status?: ServiceInstanceStatus, version?: string, keywords?: Array<string>, description?: string, dataProductType?: Array<string>, specificationId?: string, designId?: string, instanceId?: string, mmsi?: number, imo?: number, serviceType?: MaritimeServiceType, unlocode?: Array<string>, endpointUri?: string, geometry?: string, localOnly?: boolean, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public v2SearchServiceGet(name?: string, status?: ServiceInstanceStatus, version?: string, keywords?: Array<string>, description?: string, dataProductType?: Array<string>, specificationId?: string, designId?: string, instanceId?: string, mmsi?: number, imo?: number, serviceType?: MaritimeServiceType, unlocode?: Array<string>, endpointUri?: string, geometry?: string, localOnly?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public v2SearchServiceGet(name?: string, status?: ServiceInstanceStatus, version?: string, keywords?: Array<string>, description?: string, dataProductType?: Array<string>, specificationId?: string, designId?: string, instanceId?: string, mmsi?: number, imo?: number, serviceType?: MaritimeServiceType, unlocode?: Array<string>, endpointUri?: string, geometry?: string, localOnly?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public v2SearchServiceGet(name?: string, status?: ServiceInstanceStatus, version?: string, keywords?: Array<string>, description?: string, dataProductType?: Array<string>, specificationId?: string, designId?: string, instanceId?: string, mmsi?: number, imo?: number, serviceType?: MaritimeServiceType, unlocode?: Array<string>, endpointUri?: string, geometry?: string, localOnly?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

















        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('Name', <any>name);
        }
        if (status !== undefined && status !== null) {
            queryParameters = queryParameters.set('Status', <any>status);
        }
        if (version !== undefined && version !== null) {
            queryParameters = queryParameters.set('Version', <any>version);
        }
        if (keywords) {
            keywords.forEach((element) => {
                queryParameters = queryParameters.append('Keywords', <any>element);
            })
        }
        if (description !== undefined && description !== null) {
            queryParameters = queryParameters.set('Description', <any>description);
        }
        if (dataProductType) {
            dataProductType.forEach((element) => {
                queryParameters = queryParameters.append('DataProductType', <any>element);
            })
        }
        if (specificationId !== undefined && specificationId !== null) {
            queryParameters = queryParameters.set('SpecificationId', <any>specificationId);
        }
        if (designId !== undefined && designId !== null) {
            queryParameters = queryParameters.set('DesignId', <any>designId);
        }
        if (instanceId !== undefined && instanceId !== null) {
            queryParameters = queryParameters.set('InstanceId', <any>instanceId);
        }
        if (mmsi !== undefined && mmsi !== null) {
            queryParameters = queryParameters.set('Mmsi', <any>mmsi);
        }
        if (imo !== undefined && imo !== null) {
            queryParameters = queryParameters.set('Imo', <any>imo);
        }
        if (serviceType !== undefined && serviceType !== null) {
            queryParameters = queryParameters.set('ServiceType', <any>serviceType);
        }
        if (unlocode) {
            unlocode.forEach((element) => {
                queryParameters = queryParameters.append('Unlocode', <any>element);
            })
        }
        if (endpointUri !== undefined && endpointUri !== null) {
            queryParameters = queryParameters.set('EndpointUri', <any>endpointUri);
        }
        if (geometry !== undefined && geometry !== null) {
            queryParameters = queryParameters.set('geometry', <any>geometry);
        }
        if (localOnly !== undefined && localOnly !== null) {
            queryParameters = queryParameters.set('localOnly', <any>localOnly);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SearchResult>('get',`${this.basePath}/v2/searchService`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * This operation searches for service.
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public v2SearchServicePost(body?: SearchFilterObject, observe?: 'body', reportProgress?: boolean): Observable<SearchResult>;
    public v2SearchServicePost(body?: SearchFilterObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResult>>;
    public v2SearchServicePost(body?: SearchFilterObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResult>>;
    public v2SearchServicePost(body?: SearchFilterObject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SearchResult>('post',`${this.basePath}/v2/searchService`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
