# Source - https://stackoverflow.com/a/64088021
# Posted by Raedwald
# Retrieved 2026-03-31, License - CC BY-SA 4.0

  server {
    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }
  }
