/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.0.8
 * Contact: Nikolaos.Vastardis@gla-rad.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { Envelope } from './envelope';
import { GeometryFactory } from './geometryFactory';
import { Point } from './point';
import { PrecisionModel } from './precisionModel';

export interface Geometry { 
    envelope?: Geometry;
    factory?: GeometryFactory;
    userData?: any;
    dimension?: number;
    length?: number;
    empty?: boolean;
    valid?: boolean;
    srid?: number;
    coordinate?: Coordinate;
    coordinates?: Array<Coordinate>;
    numPoints?: number;
    rectangle?: boolean;
    area?: number;
    centroid?: Point;
    boundary?: Geometry;
    simple?: boolean;
    precisionModel?: PrecisionModel;
    interiorPoint?: Point;
    boundaryDimension?: number;
    envelopeInternal?: Envelope;
    geometryType?: string;
    numGeometries?: number;
}