/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.0.8
 * Contact: Nikolaos.Vastardis@gla-rad.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocDto } from './docDto';
import { Geometry } from './geometry';
import { XmlDto } from './xmlDto';

export interface InstanceDto { 
    id?: any;
    name: any;
    version: any;
    publishedAt?: any;
    lastUpdatedAt?: any;
    comment: any;
    geometry?: Geometry;
    geometryContentType?: any;
    instanceId: any;
    keywords?: any;
    status: any;
    organizationId?: any;
    unlocode?: any;
    endpointUri?: any;
    statusEndpointUri?: any;
    mmsi?: any;
    imo?: any;
    serviceTypes?: any;
    dataProductType?: any;
    instanceAsXml?: XmlDto;
    instanceAsDoc?: DocDto;
    docIds?: any;
    implementsServiceDesigns?: any;
    designsServiceSpecifications?: any;
}