/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.0.8
 * Contact: Nikolaos.Vastardis@gla-rad.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { CoordinateSequence } from './coordinateSequence';
import { Envelope } from './envelope';
import { GeometryFactory } from './geometryFactory';
import { PrecisionModel } from './precisionModel';

export interface Point { 
    envelope?: any;
    factory?: GeometryFactory;
    userData?: any;
    coordinates?: any;
    y?: any;
    x?: any;
    dimension?: any;
    empty?: any;
    coordinate?: Coordinate;
    numPoints?: any;
    boundary?: any;
    simple?: any;
    boundaryDimension?: any;
    coordinateSequence?: CoordinateSequence;
    geometryType?: any;
    length?: any;
    valid?: any;
    srid?: any;
    rectangle?: any;
    area?: any;
    centroid?: any;
    precisionModel?: PrecisionModel;
    interiorPoint?: any;
    envelopeInternal?: Envelope;
    numGeometries?: any;
}