/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.0.8
 * Contact: Nikolaos.Vastardis@gla-rad.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { CoordinateSequence } from './coordinateSequence';
import { Envelope } from './envelope';
import { GeometryFactory } from './geometryFactory';
import { PrecisionModel } from './precisionModel';

export interface Point { 
    envelope?: any;
    factory?: GeometryFactory;
    userData?: any;
    coordinates?: Array<Coordinate>;
    y?: number;
    x?: number;
    dimension?: number;
    empty?: boolean;
    coordinate?: Coordinate;
    numPoints?: number;
    boundary?: any;
    simple?: boolean;
    boundaryDimension?: number;
    coordinateSequence?: CoordinateSequence;
    geometryType?: string;
    length?: number;
    valid?: boolean;
    srid?: number;
    rectangle?: boolean;
    area?: number;
    centroid?: any;
    precisionModel?: PrecisionModel;
    interiorPoint?: any;
    envelopeInternal?: Envelope;
    numGeometries?: number;
}