/**
 * Maritime Connectivity Platform Service Registry API
 * Maritime Connectivity Platform Service Registry, developed by the MCC MSR WG
 *
 * OpenAPI spec version: 0.0.8
 * Contact: Nikolaos.Vastardis@gla-rad.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type } from './type';

export interface PrecisionModel { 
    scale?: any;
    type?: Type;
    floating?: any;
    maximumSignificantDigits?: any;
    offsetX?: any;
    offsetY?: any;
}